### ISSUE TITLE
exitstat.bpf.o missing?

### ISSUE THREAD

**Issue by markdrayton** [facebookincubator/resctl#19]
First up: `below` looks awesome! As a big `atop` fan I am excited to see development in this area. Great job.

On my pretty vanilla Arch box:

```
$ podman run --privileged --cgroupns=host --pid=host -it below/below:latest
Nov 02 12:02:39.065libbpf: failed to open /usr/facebook/below/bpf/exitstat.bpf.o: No such file or directory
 WARN Failed to initialize BPF: Failed to increase rlimit. Data collection will be degraded. You can ignore this warning or try to run with sudo.
Nov 02 12:02:39.071 ERRO%
```

I'm assuming that something is supposed to compile https://github.com/facebookincubator/resctl/blob/master/resctl/below/src/bpf/exitstat.bpf.c and put it in the path mentioned above but there's no such location in the image (in fact there's no `/usr/facebook` at all). I had a snoop about but I'm woefully unfamiliar with building Rust projects and have no idea how this is supposed to work.

**Comment by danobi** [comment]
Hi Mark,

Right now the exitstat bpf prog isn't packaged for open source yet. Internally it's shipped with the RPM. Once I finish up https://github.com/libbpf/libbpf-rs/pull/24 the bpf prog will be embedded inside of below so we won't need to worry about packaging anymore.

For now, the warning is harmless -- below will just have slightly incomplete data.

**Comment by danobi** [comment]
The bpf skeleton stuff is done now
